
Answers to questions

1. Line 9 would print "values added: 20" as thats the sum of var1 and var2.
2. Line 13 would print "final result: 20" as var is still the same as it's in the function scope.
3. Line 9 would print "values added: 20" as thats the sum of the two numbers passed to the function.
4. Line 13 would have an error because it does not know that result exists, so it thinks it is not declared because let is only visible within the block its in.
5. In line 9 there would be an error because you tried to reassign const in the previous commands, but if it went through it would print "values added: 0"
6. In line 13 it will throw an error because the variable result has not been declared in the block so it doesn't think it exists.